
services:
  libreca:
    build:
      context: .
      dockerfile: Libreca/Libreca/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
      - rabbitmq

  booksearchservice:
    build:
      context: .
      dockerfile: BookSearchService/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - db
      - rabbitmq

  notificationservice:
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - db
      - rabbitmq

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"  # Management UI
      - "5672:5672"    # AMQP protocol port
